name: Boggle Vision Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'boggle-vision-app/boggle-vision-api/**'
      - 'boggle-vision-app/boggle-vision-ui/**'

jobs:
  authenticate-with-gar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'boggle-vision'
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: boggle-vision
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          export_default_credentials: true

      - name: List images in GAR repository
        run: gcloud artifacts docker images list us-central1-docker.pkg.dev/boggle-vision/boggle-vision-webapp
