# This file contains the workflow that will build and push the  API image to the GCP Artifact Registry.
name: Boggle Vision API Deployment

# This Workflow will only run on changes to the API or UI code.
on:
  push:
    branches:
      - main
    paths:
      - "boggle-vision-app/boggle-vision-api/**"

jobs:
  # This first job will authenticate with the GCP Artifact Registry.
  # This will allow me to push images to my boggle-vision-webapp repo.
  authenticate-with-gar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "boggle-vision"
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

  # The final job will build and push the API image to the GCP Artifact Registry.
  build-and-push-api:
    needs: authenticate-with-gar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push API image
        uses: docker/build-push-action@v5.1.0
        with:
          context: boggle-vision-app/boggle-vision-api
          push: true
          tags: us-central1-docker.pkg.dev/boggle-vision/boggle-vision-webapp/boggle-vision-api:latest
