# This Workflow will deploy the Docker containers for the
# User Interface and the API to the GCP Artifact Registry
name: Boggle Vision Deployment

# This Workflow will only run whenever a push is made to the main branch
# that touches the boggle-vision-api or boggle-vision-ui directories
on:
  push:
    branches:
      - main
    paths:
      - 'boggle-vision-app\boggle-vision-api\**'
      - 'boggle-vision-app\boggle-vision-ui\**'

# Define all of the jobs that will be run in this Workflow
jobs:
  # This first job will configure Docker to be able to push/pull to my GCP Artifact Registry
  authenticate-with-gar:
    runs-on: ubuntu-latest
    steps:
      # First, use the Google Cloud Platform GitHub Action to authenticate to GCP
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: <workload_identity_provider>
          service_account: <service_account>
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: <location>-docker.pkg.dev
          username: _json_key
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: boggle-vision
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          export_default_credentials: true

      - name: List images in GAR repository
        run: gcloud artifacts docker images list us-central1-docker.pkg.dev/boggle-vision/boggle-vision-webapp
