# This file contains the workflow that will build and push the UI image to the GCP Artifact Registry.
name: Boggle Vision UI Deployment

# This Workflow will only run on changes to the UI code.
on:
  push:
    branches:
      - main
    paths:
      - "boggle-vision-app/boggle-vision-ui/**"

jobs:
  # The next job will build and push the UI image to the GCP Artifact Registry.
  build-and-push-ui:
    # needs: authenticate-with-gar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push UI image
        uses: docker/build-push-action@v5.1.0
        with:
          context: boggle-vision-app/boggle-vision-ui
          tags: us-central1-docker.pkg.dev/boggle-vision/boggle-vision-webapp/boggle-vision-ui:latest
          provenance: false
          platforms: linux/amd64
          push: true
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      - name: SSH and Update Server
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.171.53.77 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa trevbook@34.171.53.77 "echo $(date) > ~/date.txt"
