# This file contains the workflow that will build and push the  API image to the GCP Artifact Registry.
name: Boggle Vision API Deployment

# This Workflow will only run on changes to the API or UI code.
on:
  push:
    branches:
      - main
    paths:
      - "boggle-vision-app/boggle-vision-api/**"

jobs:
  # The final job will build and push the API image to the GCP Artifact Registry.
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build and push API image
        uses: docker/build-push-action@v5.1.0
        with:
          context: boggle-vision-app/boggle-vision-api
          tags: us-central1-docker.pkg.dev/boggle-vision/boggle-vision-webapp/boggle-vision-api:latest
          provenance: false
          platforms: linux/amd64
          push: true
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      - name: SSH and Update Server
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          GCR_JSON_KEY: ${{secrets.GCR_JSON_KEY}}
        run: |

          # Setting up SSH keys
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.16.90.162 >> ~/.ssh/known_hosts

          # Create a temporary file to store the GCR JSON key
          echo "$GCR_JSON_KEY" > gcr_key.json

          # Copying the deployment script and the GCR JSON key to the server
          scp -i ~/.ssh/id_rsa ./boggle-vision-app/boggle-vision-api/deployment-scripts/deploy-api.sh trevbook@34.16.90.162:/tmp/deploy-api.sh
          scp -i ~/.ssh/id_rsa ./gcr_key.json trevbook@34.16.90.162:/tmp/gcr_key.json

          # Deleting the temporary GCR JSON key file
          rm gcr_key.json

          # Running the deployment script on the server
          ssh -i ~/.ssh/id_rsa trevbook@34.16.90.162 'chmod +x /tmp/deploy-api.sh && GCR_JSON_KEY=/tmp/gcr_key.json bash /tmp/deploy-api.sh'
